### ISSUE TITLE
RemoteFileFolderLoaderTest hangs

### ISSUE THREAD

**Issue by lutzhorn** [Alfresco/alfresco-remote-api#195]
* fresh checkout of tag `alfresco-remote-api-7.35`
* empty PostgreSQL database has been created

The unit test `RemoteFileFolderLoaderTest` hangs:

```
$ mvn clean test \
  -Ddb.driver=org.postgresql.Driver \
  -Ddb.name=alfresco-6 \
  -Ddb.url=jdbc:postgresql:alfresco-6 \
  -Ddb.username=lutz \
  -Ddb.password=secret
...

[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.alfresco.heatbeat.RenditionsDataCollectorTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.288 s - in org.alfresco.heatbeat.RenditionsDataCollectorTest
[INFO] Running org.alfresco.repo.model.filefolder.RemoteFileFolderLoaderTest
```

No output is written to `target/surefire-reports/org.alfresco.repo.model.filefolder.RemoteFileFolderLoaderTest-output.txt`.

What is missing?

**Comment by killerboot** [comment]
Hi @lutzhorn,
A re you running ActiveMQ as well?
Please see how Travis does it: https://github.com/Alfresco/alfresco-remote-api/blob/master/.travis.yml#L22

**Comment by killerboot** [comment]
Please reopen if it is still valid.
